INSERT INTO users (user_id, name, user_email, password) VALUES (1, 'John Doe', 'johndoe@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (2, 'Jane Doe', 'janedoe@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (3, 'Chuchu Zhang', 'chuchu@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (4, 'Elvin Teo', 'elvin@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (5, 'Matthew Song', 'matthew@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (6, 'Quoc Dat Nguyen', 'dat@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (7, 'Teddy Hartanto', 'teddy@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (8, 'Aaron Swartz', 'aaronsw@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (9, 'Hugh Jackman', 'hugh@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (10, 'Benedict Cumberbatch', 'cumberbatch@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (11, 'Chris Pratt', 'chrispratt@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (12, 'Adele', 'adele@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (13, 'Emilia Clarke', 'missclarke@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (14, 'Laney Jones', 'laneyjones@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (15, 'Jennifer Lawrence', 'jlawrence@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (16, 'Ariana Grande', 'ariana@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (17, 'Elon Musk', 'elonmusk@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (18, 'Steve Jobs', 'stevejobs@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (19, 'Mark Manson', 'markmanson@example.com', 'password');
INSERT INTO users (user_id, name, user_email, password) VALUES (20, 'Jeff Atwood', 'jeffatwood@example.com', 'password');
