INSERT INTO users (name, user_email, password) VALUES ('John Doe', 'johndoe@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Jane Doe', 'janedoe@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Chuchu Zhang', 'chuchu@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Elvin Teo', 'elvin@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Matthew Song', 'matthew@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Quoc Dat Nguyen', 'dat@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Teddy Hartanto', 'teddy@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Aaron Swartz', 'aaronsw@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Hugh Jackman', 'hugh@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Benedict Cumberbatch', 'cumberbatch@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Chris Pratt', 'chrispratt@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Adele', 'adele@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Emilia Clarke', 'missclarke@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Laney Jones', 'laneyjones@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Jennifer Lawrence', 'jlawrence@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Ariana Grande', 'ariana@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Elon Musk', 'elonmusk@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Steve Jobs', 'stevejobs@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Mark Manson', 'markmanson@example.com', 'password');
INSERT INTO users (name, user_email, password) VALUES ('Jeff Atwood', 'jeffatwood@example.com', 'password');